# $OpenBSD$

COMMENT =		utilities for parsing numbers from strings

DISTNAME =		parsec-numbers-0.1.0
CATEGORIES =		devel

# BSD-3
PERMIT_PACKAGE =	Yes

MODULES =		lang/ghc

MODGHC_BUILD =		cabal hackage haddock register

MODGHC_PACKAGE_KEY =	LGnm1JLOShzHHxH0fDGu2Z

.include <bsd.port.mk>
