# $OpenBSD: Makefile,v 1.16 2019/05/19 19:58:51 danj Exp $

COMMENT =		binary serialization library

DISTNAME =		cereal-0.5.8.0

CATEGORIES =		devel

# BSD3
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		lang/ghc

MODGHC_BUILD =		cabal hackage haddock register

MODGHC_PACKAGE_KEY =	6rtfJLvNbgP66iuaPkuxJC

.include <bsd.port.mk>
