# $OpenBSD: Makefile,v 1.17 2019/07/12 20:44:11 sthen Exp $

COMMENT =		binary serialization library

DISTNAME =		cereal-0.5.8.0

CATEGORIES =		devel

# BSD3
PERMIT_PACKAGE =	Yes

MODULES =		lang/ghc

MODGHC_BUILD =		cabal hackage haddock register

MODGHC_PACKAGE_KEY =	6rtfJLvNbgP66iuaPkuxJC

.include <bsd.port.mk>
