# $OpenBSD$

COMMENT =		typeclass for unlifting monads to IO

DISTNAME =		unliftio-core-0.1.2.0
CATEGORIES =		devel

MAINTAINER =		Matthias Kilian <kili@openbsd.org>

# BSD3
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		lang/ghc

MODGHC_BUILD =		cabal hackage haddock register

MODGHC_PACKAGE_KEY =	DmlZdkLzX278vkyONsp8WQ

BUILD_DEPENDS =		${RUN_DEPENDS}

RUN_DEPENDS =

.include <bsd.port.mk>
