# $OpenBSD: Makefile,v 1.19 2019/07/12 20:44:35 sthen Exp $

COMMENT =		portable POSIX-compatibility layer

DISTNAME =		unix-compat-0.4.2.0
CATEGORIES =		devel

# BSD4
PERMIT_PACKAGE =	Yes

MODULES =		lang/ghc

MODGHC_BUILD =		cabal hackage haddock register

MODGHC_PACKAGE_KEY =	Lfk03egajEAGyxluAKGm9k

.include <bsd.port.mk>
