# $OpenBSD: Makefile,v 1.17 2018/01/22 21:43:46 kili Exp $

COMMENT =		portable POSIX-compatibility layer

DISTNAME =		unix-compat-0.4.1.1
REVISION =		6
CATEGORIES =		devel

MAINTAINER =		Jim Razmus II <jim@openbsd.org>

# BSD4
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		lang/ghc

MODGHC_BUILD =		cabal hackage haddock register

MODGHC_PACKAGE_KEY =	3asq9rG2PUDK0iw9Sp7ECL

.include <bsd.port.mk>
