# $OpenBSD: Makefile,v 1.5 2019/07/12 20:44:34 sthen Exp $

COMMENT =		regex-based parsing with applicative interface

DISTNAME =		regex-applicative-0.3.2.1
REVISION =		3
CATEGORIES =		devel

# BSD
PERMIT_PACKAGE =	Yes

MODULES =		lang/ghc

MODGHC_BUILD =		cabal hackage haddock register

MODGHC_PACKAGE_KEY =	7UmNQWPU54DCImdwlvepgi

.include <bsd.port.mk>
