COMMENT =		a dependently typed functional programming language

CATEGORIES =		lang

HOMEPAGE =	 	http://wiki.portal.chalmers.se/agda/ 

# BSD
PERMIT_PACKAGE =	Yes

WANTLIB =		c ffi gmp iconv m pthread util z

BUILD_DEPENDS =		devel/happy>=1.19.4 \
			devel/alex>=3.2.3

LIB_DEPENDS =		converters/libiconv \
			devel/gmp \
			devel/libffi

MODULES =		devel/cabal

MODCABAL_DATA_DIR =	src/data
MODCABAL_EXECUTABLES =	agda
MODCABAL_STEM = 	Agda
MODCABAL_VERSION = 	2.6.3
MODCABAL_REVISION = 	4
MODCABAL_MANIFEST = \
	OneTuple	0.4.1.1	0	\
	QuickCheck	2.14.3	0	\
	STMonadTrans	0.4.7	0	\
	StateVar	1.2.2	0	\
	aeson	2.2.0.0	0	\
	assoc	1.1	0	\
	async	2.2.4	3	\
	base-compat	0.13.0	0	\
	base-orphans	0.9.0	0	\
	bifunctors	5.6.1	1	\
	blaze-builder	0.4.2.2	1	\
	blaze-html	0.9.1.2	3	\
	blaze-markup	0.8.2.8	5	\
	boxes	0.1.5	0	\
	case-insensitive	1.2.1.0	0	\
	comonad	5.0.8	1	\
	contravariant	1.5.5	0	\
	data-array-byte	0.1.0.1	1	\
	data-fix	0.3.2	4	\
	data-hash	0.2.0.1	0	\
	distributive	0.6.2.1	1	\
	dlist	1.0	0	\
	edit-distance	0.2.2.1	1	\
	equivalence	0.4.1	0	\
	foldable1-classes-compat	0.1	3	\
	generically	0.1.1	1	\
	gitrev	1.3.1	0	\
	hashable	1.4.3.0	0	\
	indexed-traversable	0.1.2.1	0	\
	indexed-traversable-instances	0.1.1.2	1	\
	integer-conversion	0.1	0	\
	integer-logarithms	1.0.3.1	4	\
	monad-control	1.0.3.1	0	\
	murmur-hash	0.1.0.10	0	\
	network-uri	2.6.4.2	0	\
	parallel	3.2.2.0	6	\
	primitive	0.8.0.0	0	\
	random	1.2.1.1	0	\
	regex-base	0.94.0.2	2	\
	regex-tdfa	1.3.2.2	0	\
	scientific	0.3.7.0	5	\
	semialign	1.3	0	\
	semigroupoids	6.0.0.1	0	\
	split	0.2.3.5	0	\
	splitmix	0.1.0.4	2	\
	strict	0.5	0	\
	tagged	0.8.8	0	\
	text-iso8601	0.1	0	\
	text-short	0.1.5	2	\
	th-abstraction	0.5.0.0	0	\
	th-compat	0.1.4	3	\
	these	1.2	0	\
	time-compat	1.9.6.1	5	\
	transformers-base	0.4.6	0	\
	transformers-compat	0.7.2	0	\
	unordered-containers	0.2.19.1	2	\
	uri-encode	1.5.0.7	2	\
	utf8-string	1.0.2	0	\
	uuid-types	1.0.5	4	\
	vector	0.13.0.0	4	\
	vector-hashtables	0.1.1.3	0	\
	vector-stream	0.1.0.0	2	\
	witherable	0.4.2	4	\
	zlib	0.6.3.0	2	\


.include <bsd.port.mk>
