# $OpenBSD: Makefile,v 1.11 2019/07/12 20:49:03 sthen Exp $

COMMENT =		platform independent entropy source

DISTNAME =		entropy-0.2.1
REVISION =		8
CATEGORIES =		security

# BSD3
PERMIT_PACKAGE =	Yes

MODULES =		lang/ghc

MODGHC_BUILD =		cabal hackage haddock register

MODGHC_PACKAGE_KEY =	IfZwtxgTnXI3i1BomgGL89

.include <bsd.port.mk>
