# $OpenBSD: Makefile,v 1.10 2018/01/22 21:47:04 kili Exp $

COMMENT =		platform independent entropy source

DISTNAME =		entropy-0.2.1
REVISION =		8
CATEGORIES =		security

# BSD3
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		lang/ghc

MODGHC_BUILD =		cabal hackage haddock register

MODGHC_PACKAGE_KEY =	IfZwtxgTnXI3i1BomgGL89

.include <bsd.port.mk>
