# $OpenBSD: Makefile,v 1.20 2019/07/12 20:49:59 sthen Exp $

COMMENT =		alternative parser combinator libraries

DISTNAME =		polyparse-1.12.1
REVISION =		0
CATEGORIES =		textproc
HOMEPAGE =		http://code.haskell.org/~malcolm/polyparse/

# LGPL
PERMIT_PACKAGE =	Yes

MODULES =		lang/ghc

MODGHC_BUILD =		cabal hackage haddock register

MODGHC_PACKAGE_KEY =	FeZxex5koKh2BIaglzjzIj

BUILD_DEPENDS +=	${RUN_DEPENDS}

.include <bsd.port.mk>
