# $OpenBSD: Makefile,v 1.17 2019/09/10 13:51:27 kili Exp $

COMMENT=		provides newtype wrappers for phantom types

DISTNAME=		tagged-0.8.6
CATEGORIES=		devel

# BSD3
PERMIT_PACKAGE =	Yes

MODULES=		lang/ghc

MODGHC_BUILD =          cabal hackage haddock register

MODGHC_PACKAGE_KEY =	EiJ2F18RuD68LSMkg0Ly4r

.include <bsd.port.mk>
