# $OpenBSD: Makefile,v 1.18 2019/07/12 20:44:35 sthen Exp $

COMMENT =		tar bindings for Haskell

DISTNAME =		tar-0.5.1.0
CATEGORIES =		devel archivers

MAINTAINER =		Matthias Kilian <kili@openbsd.org>

# BSD3
PERMIT_PACKAGE =	Yes

MODULES =		lang/ghc

MODGHC_BUILD =		cabal hackage haddock register

MODGHC_PACKAGE_KEY =	HaIVxa1LuWJqqT6yxHWqZ

.include <bsd.port.mk>
