# $OpenBSD: Makefile,v 1.12 2019/07/12 20:44:11 sthen Exp $

COMMENT =		ANSI terminal package for Haskell

DISTNAME =		ansi-terminal-0.5.5
REVISION =		9
CATEGORIES =		devel

HOMEPAGE =		http://batterseapower.github.com/ansi-terminal/

MAINTAINER =		Matthias Kilian <kili@openbsd.org>

# BSD3
PERMIT_PACKAGE =	Yes

MODULES =		lang/ghc

MODGHC_BUILD =		cabal hackage haddock register

MODGHC_PACKAGE_KEY =	7QVPI56UrjJ11UKSZlbUuy

.include <bsd.port.mk>
