# $OpenBSD: Makefile,v 1.11 2018/01/22 21:40:32 kili Exp $

COMMENT =		ANSI terminal package for Haskell

DISTNAME =		ansi-terminal-0.5.5
REVISION =		9
CATEGORIES =		devel

HOMEPAGE =		http://batterseapower.github.com/ansi-terminal/

MAINTAINER =		Matthias Kilian <kili@openbsd.org>

# BSD3
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		lang/ghc

MODGHC_BUILD =		cabal hackage haddock register

MODGHC_PACKAGE_KEY =	7QVPI56UrjJ11UKSZlbUuy

.include <bsd.port.mk>
