COMMENT =		modern format for Haskell packages

CATEGORIES =		devel

HOMEPAGE =		https://github.com/sol/hpack#readme

# MIT
PERMIT_PACKAGE =	Yes

WANTLIB =		c ffi gmp iconv m pthread

MODULES =		devel/cabal

LIB_DEPENDS =		converters/libiconv \
			devel/gmp \
			devel/libffi

MODCABAL_STEM		= hpack
MODCABAL_VERSION	= 0.35.2
MODCABAL_REVISION	= 1
MODCABAL_MANIFEST	= \
	Glob	0.10.2	3	\
	OneTuple	0.4.1.1	0	\
	QuickCheck	2.14.3	0	\
	StateVar	1.2.2	0	\
	aeson	2.1.2.1	3	\
	appar	0.1.8	0	\
	asn1-encoding	0.9.6	2	\
	asn1-parse	0.9.5	0	\
	asn1-types	0.3.4	0	\
	assoc	1.1	0	\
	async	2.2.4	3	\
	attoparsec	0.14.4	3	\
	base-compat	0.13.0	0	\
	base-compat-batteries	0.13.0	0	\
	base-orphans	0.9.0	0	\
	base64-bytestring	1.2.1.0	0	\
	basement	0.0.15	0	\
	bifunctors	5.6.1	0	\
	bitvec	1.1.4.0	0	\
	blaze-builder	0.4.2.2	1	\
	byteorder	1.0.4	0	\
	case-insensitive	1.2.1.0	0	\
	cereal	0.5.8.3	0	\
	comonad	5.0.8	1	\
	conduit	1.3.5	0	\
	connection	0.3.1	1	\
	contravariant	1.5.5	0	\
	cookie	0.4.6	0	\
	cryptonite	0.30	0	\
	data-array-byte	0.1.0.1	1	\
	data-default-class	0.1.2.0	0	\
	data-fix	0.3.2	4	\
	distributive	0.6.2.1	1	\
	dlist	1.0	0	\
	foldable1-classes-compat	0.1	2	\
	generically	0.1.1	1	\
	hashable	1.4.2.0	1	\
	hourglass	0.2.12	0	\
	hsc2hs	0.68.9	0	\
	http-client	0.7.13.1	1	\
	http-client-tls	0.3.6.1	0	\
	http-types	0.12.3	0	\
	indexed-traversable	0.1.2.1	0	\
	indexed-traversable-instances	0.1.1.2	1	\
	infer-license	0.2.0	0	\
	integer-logarithms	1.0.3.1	4	\
	iproute	1.7.12	0	\
	libyaml	0.1.2	1	\
	memory	0.18.0	0	\
	mime-types	0.1.1.0	0	\
	mono-traversable	1.0.15.3	0	\
	network	3.1.4.0	0	\
	network-uri	2.6.4.2	0	\
	pem	0.2.4	0	\
	primitive	0.8.0.0	0	\
	random	1.2.1.1	0	\
	resourcet	1.3.0	0	\
	scientific	0.3.7.0	5	\
	semialign	1.3	0	\
	semigroupoids	6.0.0.1	0	\
	socks	0.6.1	0	\
	split	0.2.3.5	0	\
	splitmix	0.1.0.4	2	\
	streaming-commons	0.2.2.6	0	\
	strict	0.5	0	\
	tagged	0.8.7	0	\
	text-metrics	0.3.2	2	\
	text-short	0.1.5	2	\
	th-abstraction	0.5.0.0	0	\
	th-compat	0.1.4	2	\
	these	1.2	0	\
	time-compat	1.9.6.1	5	\
	tls	1.6.0	0	\
	transformers-compat	0.7.2	0	\
	unliftio-core	0.2.1.0	2	\
	unordered-containers	0.2.19.1	2	\
	uuid-types	1.0.5	4	\
	vector	0.13.0.0	3	\
	vector-algorithms	0.9.0.1	2	\
	vector-stream	0.1.0.0	2	\
	witherable	0.4.2	4	\
	x509	1.7.7	0	\
	x509-store	1.6.9	0	\
	x509-system	1.6.7	0	\
	x509-validation	1.6.12	0	\
	yaml	0.11.11.0	0	\
	zlib	0.6.3.0	1	\

.include <bsd.port.mk>
