# $OpenBSD: Makefile,v 1.15 2019/05/19 19:58:51 danj Exp $

COMMENT =		list-like type supporting O(1) append

DISTNAME =		dlist-0.8.0.5
CATEGORIES =		devel

# BSD3
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		lang/ghc

MODGHC_BUILD =		cabal hackage haddock register

MODGHC_PACKAGE_KEY =	FMMQwM1hD2kK7b7715Z2vG

.include <bsd.port.mk>
