# $OpenBSD: Makefile,v 1.14 2018/01/22 21:40:32 kili Exp $

COMMENT =		list-like type supporting O(1) append

DISTNAME =		dlist-0.8.0.5
REVISION =		3
CATEGORIES =		devel

MAINTAINER =		Jim Razmus II <jim@openbsd.org>

# BSD3
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		lang/ghc

MODGHC_BUILD =		cabal hackage haddock register

MODGHC_PACKAGE_KEY =	FMMQwM1hD2kK7b7715Z2vG

.include <bsd.port.mk>
