# $OpenBSD: Makefile,v 1.16 2019/07/12 20:44:12 sthen Exp $

COMMENT =		list-like type supporting O(1) append

DISTNAME =		dlist-0.8.0.5
CATEGORIES =		devel

# BSD3
PERMIT_PACKAGE =	Yes

MODULES =		lang/ghc

MODGHC_BUILD =		cabal hackage haddock register

MODGHC_PACKAGE_KEY =	FMMQwM1hD2kK7b7715Z2vG

.include <bsd.port.mk>
