# $OpenBSD$

COMMENT=		type class for sequence of bytes

DISTNAME=		byteable-0.1.1
CATEGORIES=		devel

# BSD3
PERMIT_PACKAGE =	Yes

MODULES=		lang/ghc

MODGHC_BUILD =          cabal hackage haddock register

MODGHC_PACKAGE_KEY =	9guyEXUUK503mzSnI32g2S

.include <bsd.port.mk>
