# $OpenBSD: Makefile,v 1.7 2019/07/12 20:44:35 sthen Exp $

COMMENT =		support for reading and writing UTF8 strings

DISTNAME =		utf8-string-1.0.1.1
REVISION =		4
CATEGORIES =		devel

# BSD3
PERMIT_PACKAGE =	Yes

MODULES =		lang/ghc

MODGHC_BUILD =		cabal hackage haddock register

MODGHC_PACKAGE_KEY =	Geq8jdOv4Q3LkcQoEOWDVv

.include <bsd.port.mk>
