# $OpenBSD: Makefile,v 1.5 2018/01/22 21:47:04 kili Exp $

COMMENT =		SHA message digests

DISTNAME =		SHA-1.6.4.2
REVISION =		4

CATEGORIES =		security

MAINTAINER =		Pascal Stumpf <pascal@stumpf.co>

# BSD3
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		lang/ghc

MODGHC_BUILD =		cabal hackage haddock register

MODGHC_PACKAGE_KEY =	K17FqRah5DD3xPZWh9IJHt

.include <bsd.port.mk>
