# $OpenBSD: Makefile,v 1.6 2019/07/12 20:49:03 sthen Exp $

COMMENT =		SHA message digests

DISTNAME =		SHA-1.6.4.2
REVISION =		4

CATEGORIES =		security

MAINTAINER =		Pascal Stumpf <pascal@stumpf.co>

# BSD3
PERMIT_PACKAGE =	Yes

MODULES =		lang/ghc

MODGHC_BUILD =		cabal hackage haddock register

MODGHC_PACKAGE_KEY =	K17FqRah5DD3xPZWh9IJHt

.include <bsd.port.mk>
