# $OpenBSD: Makefile,v 1.8 2019/07/12 20:44:12 sthen Exp $

COMMENT =		extensible exceptions for Haskell

DISTNAME =		extensible-exceptions-0.1.1.4
REVISION =		6
CATEGORIES =		devel

MAINTAINER =		Matthias Kilian <kili@openbsd.org>

# BSD3
PERMIT_PACKAGE =	Yes

MODULES =		lang/ghc

MODGHC_BUILD =		cabal hackage haddock register

MODGHC_PACKAGE_KEY =	KI0dG6kQM84KnSzvR2Yb0

.include <bsd.port.mk>
