# $OpenBSD: Makefile,v 1.8 2019/09/10 13:51:28 kili Exp $

COMMENT =		compat lib exposing transformers 0.3 and 0.4 types

DISTNAME =		transformers-compat-0.5.1.4
REVISION =		2
CATEGORIES =		devel

# BSD3
PERMIT_PACKAGE =	Yes

MODULES =		lang/ghc

MODGHC_BUILD =		cabal hackage haddock register

MODGHC_PACKAGE_KEY =	Ds7JyVWMMQDAstUV5nEQhw

.include <bsd.port.mk>
