# $OpenBSD: Makefile,v 1.6 2018/01/22 21:43:45 kili Exp $

COMMENT =		compat lib exposing transformers 0.3 and 0.4 types

DISTNAME =		transformers-compat-0.5.1.4
REVISION =		1
CATEGORIES =		devel

# BSD3
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		lang/ghc

MODGHC_BUILD =		cabal hackage haddock register

MODGHC_PACKAGE_KEY =	KTwLBEUpV18CvByVdyPb1a

.include <bsd.port.mk>
