# $OpenBSD: Makefile,v 1.15 2019/05/19 19:58:52 danj Exp $

COMMENT =		simple XML library

DISTNAME =		xml-1.3.7
REVISION =		12
CATEGORIES =		textproc

# BSD3
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		lang/ghc

MODGHC_BUILD =		cabal hackage haddock register

MODGHC_PACKAGE_KEY =	8a6ftauAVpI5RUSHz8NtfL

.include <bsd.port.mk>
