COMMENT =	gives suggestions on how to improve Haskell source code

CATEGORIES =	devel
HOMEPAGE =	https://github.com/ndmitchell/hlint#readme

# BSD3
PERMIT_PACKAGE =		Yes

WANTLIB =		c ffi gmp iconv m pthread util z

MODULES =		devel/cabal
MODCABAL_DATA_DIR =	data
MODCABAL_STEM		= hlint
MODCABAL_VERSION	= 3.5
MODCABAL_MANIFEST	= \
	OneTuple	0.3.1	3	\
	QuickCheck	2.14.2	0	\
	StateVar	1.2.2	0	\
	aeson	2.1.1.0	0	\
	alex	3.2.7.1	0	\
	ansi-terminal	0.11.3	0	\
	assoc	1.0.2	3	\
	attoparsec	0.14.4	2	\
	base-compat	0.12.2	0	\
	base-compat-batteries	0.12.2	0	\
	base-orphans	0.8.7	0	\
	bifunctors	5.5.13	0	\
	bitvec	1.1.3.0	0	\
	clock	0.8.3	0	\
	cmdargs	0.10.21	0	\
	colour	2.3.6	0	\
	comonad	5.0.8	1	\
	conduit	1.3.4.2	0	\
	contravariant	1.5.5	0	\
	cpphs	1.20.9.1	1	\
	data-default	0.7.1.1	0	\
	data-default-class	0.1.2.0	0	\
	data-default-instances-containers	0.0.1	0	\
	data-default-instances-dlist	0.0.1	0	\
	data-default-instances-old-locale	0.0.1	0	\
	data-fix	0.3.2	3	\
	deriving-aeson	0.2.8	1	\
	distributive	0.6.2.1	1	\
	dlist	1.0	0	\
	extra	1.7.12	0	\
	file-embed	0.0.15.0	0	\
	filepattern	0.1.3	0	\
	generically	0.1	0	\
	ghc-lib-parser	9.4.2.20220822	0	\
	ghc-lib-parser-ex	9.4.0.0	0	\
	happy	1.20.0	1	\
	hashable	1.4.1.0	0	\
	hscolour	1.24.4	0	\
	indexed-traversable	0.1.2	2	\
	indexed-traversable-instances	0.1.1.1	0	\
	integer-logarithms	1.0.3.1	3	\
	libyaml	0.1.2	0	\
	mono-traversable	1.0.15.3	0	\
	old-locale	1.0.0.7	2	\
	polyparse	1.13	5	\
	primitive	0.7.4.0	0	\
	random	1.2.1.1	0	\
	refact	0.3.0.2	0	\
	resourcet	1.2.6	0	\
	scientific	0.3.7.0	3	\
	semialign	1.2.0.1	3	\
	semigroupoids	5.3.7	0	\
	split	0.2.3.5	0	\
	splitmix	0.1.0.4	1	\
	strict	0.4.0.1	4	\
	syb	0.7.2.2	0	\
	tagged	0.8.6.1	3	\
	text-short	0.1.5	1	\
	th-abstraction	0.4.5.0	0	\
	these	1.1.1.1	6	\
	time-compat	1.9.6.1	4	\
	transformers-compat	0.7.2	0	\
	uniplate	1.6.13	1	\
	unliftio-core	0.2.0.1	2	\
	unordered-containers	0.2.19.1	1	\
	utf8-string	1.0.2	0	\
	uuid-types	1.0.5	3	\
	vector	0.13.0.0	1	\
	vector-algorithms	0.9.0.1	0	\
	vector-stream	0.1.0.0	1	\
	witherable	0.4.2	3	\
	yaml	0.11.8.0	0	\

LIB_DEPENDS =		converters/libiconv \
			devel/gmp \
			devel/libffi

.include <bsd.port.mk>
