COMMENT =	gives suggestions on how to improve Haskell source code

CATEGORIES =	devel
HOMEPAGE =	https://github.com/ndmitchell/hlint#readme

# BSD3
PERMIT_PACKAGE =		Yes

WANTLIB =		c ffi gmp iconv m pthread util z

MODULES =		devel/cabal
MODCABAL_DATA_DIR =	data
MODCABAL_STEM		= hlint
MODCABAL_VERSION	= 3.6.1
MODCABAL_MANIFEST	= \
	OneTuple	0.4.1.1	1	\
	QuickCheck	2.14.3	0	\
	StateVar	1.2.2	0	\
	aeson	2.2.1.0	1	\
	alex	3.4.0.1	0	\
	ansi-terminal	1.0	0	\
	ansi-terminal-types	0.11.5	1	\
	assoc	1.1	1	\
	attoparsec	0.14.4	5	\
	base-orphans	0.9.1	0	\
	bifunctors	5.6.1	2	\
	bitvec	1.1.5.0	0	\
	clock	0.8.4	0	\
	cmdargs	0.10.22	0	\
	colour	2.3.6	0	\
	comonad	5.0.8	2	\
	conduit	1.3.5	0	\
	contravariant	1.5.5	0	\
	cpphs	1.20.9.1	1	\
	data-default	0.7.1.1	0	\
	data-default-class	0.1.2.0	0	\
	data-default-instances-containers	0.0.1	0	\
	data-default-instances-dlist	0.0.1	0	\
	data-default-instances-old-locale	0.0.1	0	\
	data-fix	0.3.2	5	\
	deriving-aeson	0.2.9	1	\
	distributive	0.6.2.1	1	\
	dlist	1.0	1	\
	extra	1.7.14	0	\
	file-embed	0.0.15.0	0	\
	filepattern	0.1.3	0	\
	generically	0.1.1	2	\
	ghc-lib-parser	9.6.3.20231121	0	\
	ghc-lib-parser-ex	9.6.0.2	0	\
	happy	1.20.1.1	0	\
	hashable	1.4.3.0	1	\
	hscolour	1.25	0	\
	indexed-traversable	0.1.3	0	\
	indexed-traversable-instances	0.1.1.2	2	\
	integer-conversion	0.1.0.1	1	\
	integer-logarithms	1.0.3.1	5	\
	libyaml	0.1.2	1	\
	mono-traversable	1.0.15.3	0	\
	network-uri	2.6.4.2	1	\
	old-locale	1.0.0.7	2	\
	polyparse	1.13	9	\
	primitive	0.9.0.0	0	\
	random	1.2.1.1	1	\
	refact	0.3.0.2	0	\
	resourcet	1.3.0	0	\
	scientific	0.3.7.0	7	\
	semialign	1.3	1	\
	semigroupoids	6.0.0.1	1	\
	split	0.2.4	0	\
	splitmix	0.1.0.5	0	\
	strict	0.5	1	\
	syb	0.7.2.4	0	\
	tagged	0.8.8	0	\
	text-iso8601	0.1	1	\
	text-short	0.1.5	3	\
	th-abstraction	0.6.0.0	1	\
	th-compat	0.1.4	3	\
	these	1.2	1	\
	time-compat	1.9.6.1	6	\
	transformers-compat	0.7.2	0	\
	uniplate	1.6.13	1	\
	unliftio-core	0.2.1.0	3	\
	unordered-containers	0.2.19.1	3	\
	utf8-string	1.0.2	0	\
	uuid-types	1.0.5.1	0	\
	vector	0.13.1.0	0	\
	vector-algorithms	0.9.0.1	3	\
	vector-stream	0.1.0.0	3	\
	witherable	0.4.2	4	\
	yaml	0.11.11.2	2	\

LIB_DEPENDS =		converters/libiconv \
			devel/gmp \
			devel/libffi

.include <bsd.port.mk>
