# $OpenBSD: Makefile,v 1.2 2018/01/22 21:44:46 kili Exp $

COMMENT =		model for human colour/color perception

DISTNAME =		colour-2.3.4
CATEGORIES =		devel graphics

# BSD3
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		lang/ghc

MODGHC_BUILD =		cabal hackage haddock register

MODGHC_PACKAGE_KEY =	BYzTQyKoQ9LK29pbkBo2SY

.include <bsd.port.mk>
