# $OpenBSD: Makefile,v 1.3 2019/07/12 20:47:00 sthen Exp $

COMMENT =		model for human colour/color perception

DISTNAME =		colour-2.3.4
CATEGORIES =		devel graphics

# BSD3
PERMIT_PACKAGE =	Yes

MODULES =		lang/ghc

MODGHC_BUILD =		cabal hackage haddock register

MODGHC_PACKAGE_KEY =	BYzTQyKoQ9LK29pbkBo2SY

.include <bsd.port.mk>
