# $OpenBSD: Makefile,v 1.5 2019/07/12 20:44:12 sthen Exp $

COMMENT =		set and multiset operations on ordered lists

DISTNAME =		data-ordlist-0.4.7.0
REVISION =		3
CATEGORIES =		devel

# BSD3
PERMIT_PACKAGE =	Yes

MODULES =		lang/ghc

MODGHC_BUILD =		cabal hackage haddock register

MODGHC_PACKAGE_KEY =	JijOptHq8X5AysaK6Liyhk

.include <bsd.port.mk>
