# $OpenBSD: Makefile,v 1.20 2019/09/10 13:51:29 kili Exp $

COMMENT =		efficient conversion of values to readable byte strings

DISTNAME =		bytestring-show-0.3.5.6
REVISION =		7
CATEGORIES =		textproc

# BSD3
PERMIT_PACKAGE =	Yes

MODULES =		lang/ghc

MODGHC_BUILD =		cabal hackage haddock register

MODGHC_PACKAGE_KEY =	9LsbtUHXG0YJS89oK68DPL

.include <bsd.port.mk>
