# $OpenBSD: Makefile,v 1.16 2019/07/12 20:44:11 sthen Exp $

COMMENT =		locate directory of original program

DISTNAME =		FindBin-0.0.5
REVISION =		10
CATEGORIES =		devel
HOMEPAGE =		https://github.com/audreyt/findbin

# BSD3
PERMIT_PACKAGE =	Yes

MODULES =		lang/ghc
MODGHC_BUILD =		cabal hackage haddock register

MODGHC_PACKAGE_KEY =	6QSFjAP4vvy4WhAg9UfF4U

.include <bsd.port.mk>
