# $OpenBSD: Makefile,v 1.15 2018/01/22 21:40:32 kili Exp $

COMMENT =		locate directory of original program

DISTNAME =		FindBin-0.0.5
REVISION =		10
CATEGORIES =		devel
HOMEPAGE =		https://github.com/audreyt/findbin

# BSD3
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		lang/ghc
MODGHC_BUILD =		cabal hackage haddock register

MODGHC_PACKAGE_KEY =	6QSFjAP4vvy4WhAg9UfF4U

.include <bsd.port.mk>
