# $OpenBSD: Makefile,v 1.10 2018/01/22 21:46:26 kili Exp $

COMMENT =		Haskell package for determining the hostname

DISTNAME =		hostname-1.0
REVISION =		8
CATEGORIES =		devel net

MAINTAINER =		Matthias Kilian <kili@openbsd.org>

# BSD3
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		lang/ghc

MODGHC_BUILD =		cabal hackage haddock register

MODGHC_PACKAGE_KEY =	96RwzZJKf0mHYnt0kjXkqR

.include <bsd.port.mk>
