#!/bin/sh
#
# Migrate a cabal port from inline MODCABAL_MANIFEST to cabal-manifest.inc
#
# Usage: migrate-to-inc.sh <port-directory>
#

set -e

if [ $# -ne 1 ]; then
	echo "Usage: $0 <port-directory>" >&2
	exit 1
fi

PORT_DIR="$1"

if [ ! -d "$PORT_DIR" ]; then
	echo "Error: Directory $PORT_DIR does not exist" >&2
	exit 1
fi

if [ ! -f "$PORT_DIR/Makefile" ]; then
	echo "Error: No Makefile found in $PORT_DIR" >&2
	exit 1
fi

cd "$PORT_DIR"

# Check if already migrated
if [ -f "cabal-manifest.inc" ]; then
	echo "Already migrated: cabal-manifest.inc exists"
	exit 0
fi

# Extract the cabal-bundler command from comments
BUNDLER_CMD=$(grep -E '^\s*#.*cabal-bundler' Makefile | head -1 | sed 's/^[[:space:]]*#[[:space:]]*//')

if [ -z "$BUNDLER_CMD" ]; then
	echo "Warning: No cabal-bundler command found in comments"
	BUNDLER_CMD="cabal-bundler (command not recorded)"
fi

# Extract MODCABAL_MANIFEST content
# This is tricky because it can be multi-line with backslash continuation
echo "Extracting MODCABAL_MANIFEST..."

awk '
BEGIN { in_manifest = 0; }
/^MODCABAL_MANIFEST[[:space:]]*=/ {
	in_manifest = 1;
	# Skip the "MODCABAL_MANIFEST =" part
	line = $0;
	sub(/^MODCABAL_MANIFEST[[:space:]]*=[[:space:]]*/, "", line);
	sub(/\\[[:space:]]*$/, "", line);
	if (line != "") print line;
	next;
}
in_manifest == 1 {
	if ($0 ~ /^[[:space:]]/) {
		# Continuation line
		line = $0;
		sub(/^[[:space:]]+/, "", line);
		sub(/\\[[:space:]]*$/, "", line);
		if (line != "") print line;
		if ($0 !~ /\\[[:space:]]*$/) {
			in_manifest = 0;
		}
	} else {
		in_manifest = 0;
	}
}
' Makefile > /tmp/manifest_data.$$

# Check if we extracted anything
if [ ! -s /tmp/manifest_data.$$ ]; then
	echo "Warning: No MODCABAL_MANIFEST found in Makefile (port has no dependencies)"
	# Create an empty manifest file for consistency
	{
		echo "# Generated by: $BUNDLER_CMD"
		echo ""
		echo "# This port has no Haskell dependencies"
	} > cabal-manifest.inc
	rm -f /tmp/manifest_data.$$

	# Still update the Makefile to include the .inc file for consistency
	echo "Creating empty cabal-manifest.inc for consistency..."
	echo "Updating Makefile..."

	# Create a backup
	cp Makefile Makefile.bak

	# Add the .include line before the final .include <bsd.port.mk>
	awk '
	/^\.include <bsd.port.mk>/ {
		if (!included) {
			print ".include \"cabal-manifest.inc\"";
			print "";
			included = 1;
		}
	}
	{ print }
	' Makefile.bak > Makefile

	echo "Migration complete!"
	echo "  - Created: cabal-manifest.inc (empty)"
	echo "  - Updated: Makefile"
	echo "  - Backup:  Makefile.bak"
	exit 0
fi

# Generate cabal-manifest.inc
echo "Generating cabal-manifest.inc..."
{
	echo "# Generated by: $BUNDLER_CMD"
	echo ""
	# Read triples and output in new format
	while read -r pkg ver rev; do
		# Skip empty lines
		if [ -n "$pkg" ]; then
			echo "MODCABAL_MANIFEST += $pkg $ver $rev"
		fi
	done < /tmp/manifest_data.$$
} > cabal-manifest.inc

rm -f /tmp/manifest_data.$$

echo "Created cabal-manifest.inc with $(grep -c '^MODCABAL_MANIFEST' cabal-manifest.inc) dependencies"

# Now update the Makefile to include the .inc file instead of inline manifest
echo "Updating Makefile..."

# Create a backup
cp Makefile Makefile.bak

# Use awk to process the Makefile
awk '
BEGIN {
	in_manifest = 0;
	manifest_replaced = 0;
}

# Found start of MODCABAL_MANIFEST
/^MODCABAL_MANIFEST[[:space:]]*=/ {
	in_manifest = 1;
	if (!manifest_replaced) {
		print ".include \"cabal-manifest.inc\"";
		manifest_replaced = 1;
	}
	# Skip this line and check if it continues
	if ($0 !~ /\\[[:space:]]*$/) {
		in_manifest = 0;
	}
	next;
}

# In manifest continuation
in_manifest == 1 {
	if ($0 ~ /^[[:space:]]/ || $0 ~ /^[[:space:]]*[^[:space:]].*\\[[:space:]]*$/) {
		# This is a continuation line, skip it
		if ($0 !~ /\\[[:space:]]*$/) {
			in_manifest = 0;
		}
		next;
	} else {
		# End of manifest
		in_manifest = 0;
	}
}

# Print all other lines
{ print }
' Makefile.bak > Makefile

echo "Migration complete!"
echo "  - Created: cabal-manifest.inc"
echo "  - Updated: Makefile"
echo "  - Backup:  Makefile.bak"
echo ""
echo "Please verify the changes with: diff -u Makefile.bak Makefile"
