#!/bin/sh
#
# Update a cabal port to a new version
#
# Usage: update-cabal-port.sh <port-directory> [options]
#
# Options:
#   --version <ver>    Update to specific version (default: latest from Hackage)
#   --dry-run          Show what would be done without making changes
#   --no-makesum       Skip running 'make makesum'
#   --no-package       Skip running 'make package'
#   --help             Show this help message
#

set -e

usage() {
	sed -n '2,/^$/s/^# \?//p' < "$0"
	exit "${1:-0}"
}

# Parse arguments
PORT_DIR=""
VERSION=""
DRY_RUN=0
RUN_MAKESUM=1
RUN_PACKAGE=0

while [ $# -gt 0 ]; do
	case "$1" in
		--version)
			VERSION="$2"
			shift 2
			;;
		--dry-run)
			DRY_RUN=1
			shift
			;;
		--no-makesum)
			RUN_MAKESUM=0
			shift
			;;
		--package)
			RUN_PACKAGE=1
			shift
			;;
		--no-package)
			RUN_PACKAGE=0
			shift
			;;
		--help|-h)
			usage 0
			;;
		-*)
			echo "Unknown option: $1" >&2
			usage 1
			;;
		*)
			if [ -z "$PORT_DIR" ]; then
				PORT_DIR="$1"
			else
				echo "Error: Multiple port directories specified" >&2
				usage 1
			fi
			shift
			;;
	esac
done

if [ -z "$PORT_DIR" ]; then
	echo "Error: Port directory required" >&2
	usage 1
fi

if [ ! -d "$PORT_DIR" ]; then
	echo "Error: Directory $PORT_DIR does not exist" >&2
	exit 1
fi

if [ ! -f "$PORT_DIR/Makefile" ]; then
	echo "Error: No Makefile found in $PORT_DIR" >&2
	exit 1
fi

cd "$PORT_DIR"
PORT_NAME=$(basename "$PWD")
CATEGORY=$(basename "$(dirname "$PWD")")
FULL_NAME="$CATEGORY/$PORT_NAME"

echo "==> Updating cabal port: $FULL_NAME"
echo ""

# Extract current configuration from Makefile
echo "==> Extracting current configuration..."

MODCABAL_STEM=$(awk '/^MODCABAL_STEM[[:space:]]*=/ {
	for(i=2; i<=NF; i++) if ($i !~ /^#/) printf "%s ", $i;
	print "";
}' Makefile | sed 's/[[:space:]]*$//')

CURRENT_VERSION=$(awk '/^MODCABAL_VERSION[[:space:]]*=/ {
	for(i=2; i<=NF; i++) if ($i !~ /^#/) printf "%s ", $i;
	print "";
}' Makefile | sed 's/[[:space:]]*$//')

MODCABAL_FLAGS=$(awk '/^MODCABAL_FLAGS[[:space:]]*=/ {
	for(i=2; i<=NF; i++) if ($i !~ /^#/) printf "%s ", $i;
	print "";
}' Makefile | sed 's/[[:space:]]*$//')

MODCABAL_EXECUTABLES=$(awk '/^MODCABAL_EXECUTABLES[[:space:]]*=/ {
	for(i=2; i<=NF; i++) if ($i !~ /^#/) printf "%s ", $i;
	print "";
}' Makefile | sed 's/[[:space:]]*$//')

# Extract cabal-bundler command from existing cabal-manifest.inc or Makefile comments
BUNDLER_CMD=""
if [ -f "cabal-manifest.inc" ]; then
	BUNDLER_CMD=$(sed -n '1s/^# Generated by: //p' cabal-manifest.inc)
elif [ -f "Makefile" ]; then
	BUNDLER_CMD=$(grep -E '^\s*#.*cabal-bundler' Makefile | head -1 | sed 's/^[[:space:]]*#[[:space:]]*//')
fi

if [ -z "$MODCABAL_STEM" ]; then
	echo "Error: Could not determine MODCABAL_STEM from Makefile" >&2
	exit 1
fi

echo "  Package:         $MODCABAL_STEM"
echo "  Current version: $CURRENT_VERSION"
[ -n "$MODCABAL_FLAGS" ] && echo "  Flags:           $MODCABAL_FLAGS"
[ -n "$MODCABAL_EXECUTABLES" ] && echo "  Executables:     $MODCABAL_EXECUTABLES"
[ -n "$BUNDLER_CMD" ] && echo "  Bundler command: $BUNDLER_CMD"
echo ""

# Determine target version
if [ -z "$VERSION" ]; then
	echo "==> Fetching latest version from Hackage..."
	# Query Hackage API for latest version
	HACKAGE_URL="https://hackage.haskell.org/package/$MODCABAL_STEM/preferred"

	if command -v curl > /dev/null 2>&1; then
		HACKAGE_JSON=$(curl -sS "$HACKAGE_URL" || echo "")
	elif command -v ftp > /dev/null 2>&1; then
		# OpenBSD ftp can fetch HTTP URLs
		HACKAGE_JSON=$(ftp -o - "$HACKAGE_URL" 2>/dev/null || echo "")
	else
		echo "Error: Neither curl nor ftp available to fetch from Hackage" >&2
		exit 1
	fi

	if [ -z "$HACKAGE_JSON" ]; then
		echo "Warning: Could not fetch preferred version from Hackage"
		echo "Trying package info page..."

		# Fallback: try to get the latest version from package page
		PKG_URL="https://hackage.haskell.org/package/$MODCABAL_STEM"
		if command -v curl > /dev/null 2>&1; then
			VERSION=$(curl -sS "$PKG_URL" | grep -o "$MODCABAL_STEM-[0-9][0-9.]*" | head -1 | sed "s/^$MODCABAL_STEM-//")
		elif command -v ftp > /dev/null 2>&1; then
			VERSION=$(ftp -o - "$PKG_URL" 2>/dev/null | grep -o "$MODCABAL_STEM-[0-9][0-9.]*" | head -1 | sed "s/^$MODCABAL_STEM-//")
		fi
	else
		# Parse JSON for "normal-version" field
		# Simple parsing without jq dependency
		VERSION=$(echo "$HACKAGE_JSON" | sed -n 's/.*"normal-version"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -1)
	fi

	if [ -z "$VERSION" ]; then
		echo "Error: Could not determine latest version from Hackage" >&2
		echo "Please specify version with --version" >&2
		exit 1
	fi

	echo "  Latest version: $VERSION"
else
	echo "  Target version: $VERSION (specified)"
fi
echo ""

# Check if already at target version
if [ "$CURRENT_VERSION" = "$VERSION" ]; then
	echo "==> Already at version $VERSION, nothing to do"
	exit 0
fi

# Construct cabal-bundler command
echo "==> Constructing cabal-bundler command..."

BUNDLER_ARGS="--openbsd ${MODCABAL_STEM}-${VERSION}"

# Add executable flags if specified
if [ -n "$MODCABAL_EXECUTABLES" ]; then
	# Only add --executable if it's different from MODCABAL_STEM
	if [ "$MODCABAL_EXECUTABLES" != "$MODCABAL_STEM" ] && [ "$MODCABAL_EXECUTABLES" != "\${MODCABAL_STEM}" ]; then
		for exe in $MODCABAL_EXECUTABLES; do
			BUNDLER_ARGS="$BUNDLER_ARGS --executable $exe"
		done
	fi
fi

CABAL_BUNDLER_CMD="cabal-bundler $BUNDLER_ARGS"
echo "  Command: $CABAL_BUNDLER_CMD"
echo ""

if [ $DRY_RUN -eq 1 ]; then
	echo "==> DRY RUN: Would execute the following steps:"
	echo "  1. Run: $CABAL_BUNDLER_CMD"
	echo "  2. Generate new cabal-manifest.inc"
	echo "  3. Update MODCABAL_VERSION to $VERSION in Makefile"
	[ $RUN_MAKESUM -eq 1 ] && echo "  4. Run: make makesum"
	[ $RUN_PACKAGE -eq 1 ] && echo "  5. Run: make package"
	exit 0
fi

# Run cabal-bundler
echo "==> Running cabal-bundler..."
if ! $CABAL_BUNDLER_CMD > /tmp/cabal-bundler-output.$$ 2>&1; then
	echo "Error: cabal-bundler failed" >&2
	cat /tmp/cabal-bundler-output.$$ >&2
	rm -f /tmp/cabal-bundler-output.$$
	exit 1
fi

echo "  cabal-bundler completed successfully"

# Extract the manifest from cabal-bundler output
# cabal-bundler outputs Makefile fragments, we need to extract MODCABAL_MANIFEST
if ! grep -q '^MODCABAL_MANIFEST' /tmp/cabal-bundler-output.$$; then
	echo "Error: cabal-bundler output doesn't contain MODCABAL_MANIFEST" >&2
	cat /tmp/cabal-bundler-output.$$ >&2
	rm -f /tmp/cabal-bundler-output.$$
	exit 1
fi

# Generate new cabal-manifest.inc
echo "==> Generating cabal-manifest.inc..."

{
	echo "# Generated by: $CABAL_BUNDLER_CMD"
	echo ""

	# Extract and reformat manifest
	awk '
	BEGIN { in_manifest = 0; }
	/^MODCABAL_MANIFEST[[:space:]]*=/ {
		in_manifest = 1;
		line = $0;
		sub(/^MODCABAL_MANIFEST[[:space:]]*=[[:space:]]*/, "", line);
		sub(/\\[[:space:]]*$/, "", line);
		if (line != "") print line;
		next;
	}
	in_manifest == 1 {
		if ($0 ~ /^[[:space:]]/) {
			line = $0;
			sub(/^[[:space:]]+/, "", line);
			sub(/\\[[:space:]]*$/, "", line);
			if (line != "") print line;
			if ($0 !~ /\\[[:space:]]*$/) {
				in_manifest = 0;
			}
		} else {
			in_manifest = 0;
		}
	}
	' /tmp/cabal-bundler-output.$$ | \
	while read -r pkg ver rev; do
		if [ -n "$pkg" ]; then
			echo "MODCABAL_MANIFEST += $pkg $ver $rev"
		fi
	done
} > cabal-manifest.inc

rm -f /tmp/cabal-bundler-output.$$

DEP_COUNT=$(grep -c '^MODCABAL_MANIFEST' cabal-manifest.inc || echo 0)
echo "  Generated cabal-manifest.inc with $DEP_COUNT dependencies"

# Update MODCABAL_VERSION in Makefile
echo "==> Updating MODCABAL_VERSION in Makefile..."

if ! grep -q '^MODCABAL_VERSION[[:space:]]*=' Makefile; then
	echo "Error: MODCABAL_VERSION not found in Makefile" >&2
	exit 1
fi

# Create backup
cp Makefile Makefile.update-backup

# Update the version
sed -i.bak "s/^MODCABAL_VERSION[[:space:]]*=.*/MODCABAL_VERSION =	${VERSION}/" Makefile
rm -f Makefile.bak

echo "  Updated MODCABAL_VERSION: $CURRENT_VERSION -> $VERSION"

# Ensure Makefile includes cabal-manifest.inc
if ! grep -q 'cabal-manifest.inc' Makefile; then
	echo "Warning: Makefile doesn't include cabal-manifest.inc"
	echo "You may need to migrate the port first using migrate-to-inc.sh"
fi

# Run make makesum
if [ $RUN_MAKESUM -eq 1 ]; then
	echo ""
	echo "==> Running make makesum..."
	if make makesum; then
		echo "  Checksums updated successfully"
	else
		echo "Error: make makesum failed" >&2
		echo "Rolling back changes..." >&2
		mv Makefile.update-backup Makefile
		exit 1
	fi
	rm -f Makefile.update-backup
fi

# Run make package
if [ $RUN_PACKAGE -eq 1 ]; then
	echo ""
	echo "==> Running make package..."
	if make package; then
		echo "  Package built successfully"
	else
		echo "Warning: make package failed" >&2
		echo "You may need to:"
		echo "  - Update patches manually"
		echo "  - Fix PLIST issues"
		echo "  - Adjust build flags"
		exit 1
	fi
fi

echo ""
echo "==> Update complete!"
echo "  Port:        $FULL_NAME"
echo "  Old version: $CURRENT_VERSION"
echo "  New version: $VERSION"
echo "  Dependencies: $DEP_COUNT"
echo ""
echo "Next steps:"
echo "  1. Review changes: git diff"
echo "  2. Test build:     make package"
echo "  3. Test install:   make install"
echo "  4. Run tests:      make test (if available)"
