# $OpenBSD: Makefile,v 1.16 2019/07/12 20:44:11 sthen Exp $

COMMENT=		fast base64 encodings and decoding for ByteStrings

DISTNAME=		base64-bytestring-1.0.0.0
REVISION=		9
CATEGORIES=		devel

# 3-clause BSD
PERMIT_PACKAGE =	Yes

MODULES=		lang/ghc

MODGHC_BUILD =          cabal hackage haddock register

MODGHC_PACKAGE_KEY =	FInYrLp5hdmCCyamKwEulx

.include <bsd.port.mk>
