# $OpenBSD: Makefile,v 1.3 2019/07/12 20:49:03 sthen Exp $

# used by cabal-install

COMMENT=		fast, pure and practical SHA-256 implementation

DISTNAME=		cryptohash-sha256-0.11.101.0
REVISION=		0
CATEGORIES=		security

# BSD3
PERMIT_PACKAGE =	Yes

MODULES=		lang/ghc

MODGHC_BUILD =          cabal hackage haddock register

MODGHC_PACKAGE_KEY =	4hEdGCusAXMBLiu8h413L1

.include <bsd.port.mk>
