# $OpenBSD: Makefile,v 1.5 2019/09/10 13:51:27 kili Exp $

COMMENT =		file and directory path manipulations

DISTNAME =		system-filepath-0.4.14
CATEGORIES =		devel

# BSD3
PERMIT_PACKAGE =	Yes

MODULES =		lang/ghc
MODGHC_BUILD =		cabal hackage haddock register

MODGHC_PACKAGE_KEY =	FRUtJu5zAWTG9MKrRBz8D6

BUILD_DEPENDS =		${RUN_DEPENDS}


.include <bsd.port.mk>
