# $OpenBSD: Makefile,v 1.3 2018/01/22 21:43:45 kili Exp $

COMMENT =		file and directory path manipulations

DISTNAME =		system-filepath-0.4.14
CATEGORIES =		devel

# BSD3
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		lang/ghc
MODGHC_BUILD =		cabal hackage haddock register

MODGHC_PACKAGE_KEY =	FRUtJu5zAWTG9MKrRBz8D6

BUILD_DEPENDS =		${RUN_DEPENDS}


.include <bsd.port.mk>
