# $OpenBSD: Makefile,v 1.11 2018/01/22 21:40:32 kili Exp $

COMMENT=		fast base16 (hex) encoding and decoding for ByteStrings

DISTNAME=		base16-bytestring-0.1.1.5
REVISION=		6
CATEGORIES=		devel

# BSD3
PERMIT_PACKAGE_CDROM =	Yes

MODULES=		lang/ghc

MODGHC_BUILD =          cabal hackage haddock register

MODGHC_PACKAGE_KEY =	Cbny7PPJRBc3NO5kr5Cia8

.include <bsd.port.mk>
